// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Beemouser
{
	public partial class CommitmentPreferencesController : NSViewController
	{
		public CommitmentPreferencesController (IntPtr handle) : base (handle)
		{
		}
	}
}
