// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

using SQLite;
using System.Linq;

using Beemouser.Domain.Models;
using Beemouser.DbContexts;
using Microsoft.EntityFrameworkCore;

namespace Beemouser
{
	public partial class GeneralPreferencesController : NSViewController
	{
		public GeneralPreferencesController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			
			UpdateRecordingSinceLabel();
		}

		private void UpdateRecordingSinceLabel()
		{
			var firstClick = GetFirstClickTime();

			if (firstClick != null)
            {
                // Todo: Localize.
                RecordingSinceLabel.StringValue = GetFirstClickTime()?.ToString("g");
			}
		}

		private DateTime? GetFirstClickTime()
        {
			using (var context = new ClickContext())
            {
				var firstClick = context.Clicks.FirstOrDefault()?.ClickedAt;

				return firstClick;
            }
        }
	}
}
