// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

using SQLite;
using System.Linq;

using Beemouser.Domain.Models;
using Beemouser.DbContexts;

namespace Beemouser
{
	public partial class GeneralPreferencesController : NSViewController
	{
		public GeneralPreferencesController (IntPtr handle) : base (handle)
		{
		}

		private void UpdateRecordingSinceLabel()
		{
			using (var context = new ClickContext())
            {

				RecordingSinceLabel.StringValue = GetFirstDataPoint().ToString();
            }
		}

		private DateTime GetFirstDataPoint()
        {
			using (var context = new ClickContext())
            {
				var firstClick = context.Clicks.FirstOrDefault();

				return firstClick.ClickedAt;
            }
        }
	}
}
